// docs/pages/examples/TodoApp.vue
<template>
  <section>
    <input v-model="newTodo" @keydown.enter="addTodo" placeholder="Add Todo">
    <select v-model="visibility">
      <option v-for="filterName in Object.keys(filters)" :key="filterName">{{filterName}}</option>
    </select>
    <ul>
      <li v-for="todo in filteredTodos" :key="todo.id" :class="{ completed: todo.completed }">
        <input type="checkbox" v-model="todo.completed">
        <span>{{todo.title}}</span>
      </li>
    </ul>
  </section>
</template>

<script>
const filters = {
  all(todos) {
    return todos
  },
  active(todos) {
    return todos.filter(todo => !todo.completed)
  },
  completed(todos) {
    return todos.filter(todo => todo.completed)
  },
}

export default {
  data() {
    return {
      todos: [
        {
          id: 1,
          title: 'apple',
          completed: false,
        },
        {
          id: 2,
          title: 'banana',
          completed: false,
        },
      ],
      newTodo: '',
      visibility: 'all',
      filters,
    }
  },
  computed: {
    filteredTodos() {
      return filters[this.visibility](this.todos)
    },
  },
  methods: {
    addTodo() {
      const value = this.newTodo && this.newTodo.trim()
      if (!value) {
        return
      }
      this.todos.push({
        id: Math.random(),
        title: value,
        completed: false,
      })
      this.newTodo = ''
    },
  },
}
</script>

<style>
ul {
  margin: 0;
  padding: 0;
}
li {
  list-style: none;
  margin: 0;
  padding: 0;
}
</style>

// docs/pages/examples/TodoApp.svelte
<template>
	<section>
		<input bind:value="newTodo" @keydown.enter="addTodo" placeholder="Add Todo">
		<select bind:value="visibility">
			{#each Object.keys(filters) as filterName}
			<option>{filterName}</option>
			{/each}
		</select>
		<ul>
			{#each filteredTodos as todo}
			<li>
				<input type="checkbox" bind:value=todo.completed>
				<span>{todo.title}</span>
			</li>
			{/each}
		</ul>
	</section>
</template>

<script>
  const filters = {
    all(todos) {
      return todos
    },
    active(todos) {
      return todos.filter(todo => !todo.completed)
    },
    completed(todos) {
      return todos.filter(todo => todo.completed)
    },
  }

  let todos = [
    {
      title: 'apple',
      completed: false,
    },
    {
      title: 'banana',
      completed: false,
    },
  ]
  let newTodo = ''
  let visibility = 'all'
  $: filteredTodos = filters[visibility](todos)

  function addTodo() {
    const value = newTodo && newTodo.trim()
    if (!value) {
      return
    }
    todos = [
      ...todos,
      {
        title: value,
        completed: false,
      },
    ]
    newTodo = ''
  }
</script>

<style>
  ul {
    margin: 0;
    padding: 0;
  }
  li {
    list-style: none;
    margin: 0;
    padding: 0;
  }
</style>
