// docs/pages/examples/TodoApp.jsx
import { useState } from 'react'

const filters = {
  all(todos) {
    return todos
  },
  active(todos) {
    return todos.filter(todo => !todo.completed)
  },
  completed(todos) {
    return todos.filter(todo => todo.completed)
  },
}

function App() {
  const [todos, setTodos] = useState([
    {
      id: 1,
      title: 'apple',
      completed: false,
    },
    {
      id: 2,
      title: 'banana',
      completed: false,
    },
  ])
  const [visibility, setVisibility] = useState('all')
  const [newTodo, setNewTodo] = useState('')
  const filteredTodos = filters[visibility](todos)
  function addTodo() {
    const value = newTodo && newTodo.trim()
    if (!value) {
      return
    }
    setTodos([
      ...todos,
      {
        id: Math.random(),
        title: value,
        completed: false,
      },
    ])
    setNewTodo('')
  }
  function toggleCompleted(payload) {
    setTodos(
      todos.map(todo => {
        if (todo.id !== payload.id) {
          return todo
        }
        return {
          ...todo,
          completed: !todo.completed,
        }
      })
    )
  }
  return (
    <section>
      <input
        placeholder="Add Todo"
        value={newTodo}
        onChange={event => setNewTodo(event.target.value)}
        onKeyDown={event => {
          if (event.key === 'Enter') {
            addTodo()
          }
        }}
      />
      <select onChange={event => setVisibility(event.target.value)}>
        {Object.keys(filters).map(filterName => (
          <option key={filterName}>{filterName}</option>
        ))}
      </select>
      <ul>
        {filteredTodos.map(todo => (
          <li key={todo.id}>
            <input
              type="checkbox"
              checked={todo.completed}
              onChange={() => toggleCompleted(todo)}
            />
            <span>{todo.title}</span>
          </li>
        ))}
      </ul>
    </section>
  )
}

// docs/pages/examples/TodoApp.vue
<template>
  <section>
    <input v-model="newTodo" @keydown.enter="addTodo" placeholder="Add Todo">
    <select v-model="visibility">
      <option v-for="filterName in Object.keys(filters)" :key="filterName">{{filterName}}</option>
    </select>
    <ul>
      <li v-for="todo in filteredTodos" :key="todo.id" :class="{ completed: todo.completed }">
        <input type="checkbox" v-model="todo.completed">
        <span>{{todo.title}}</span>
      </li>
    </ul>
  </section>
</template>

<script>
const filters = {
  all(todos) {
    return todos
  },
  active(todos) {
    return todos.filter(todo => !todo.completed)
  },
  completed(todos) {
    return todos.filter(todo => todo.completed)
  },
}

export default {
  data() {
    return {
      todos: [
        {
          id: 1,
          title: 'apple',
          completed: false,
        },
        {
          id: 2,
          title: 'banana',
          completed: false,
        },
      ],
      newTodo: '',
      visibility: 'all',
      filters,
    }
  },
  computed: {
    filteredTodos() {
      return filters[this.visibility](this.todos)
    },
  },
  methods: {
    addTodo() {
      const value = this.newTodo && this.newTodo.trim()
      if (!value) {
        return
      }
      this.todos.push({
        id: Math.random(),
        title: value,
        completed: false,
      })
      this.newTodo = ''
    },
  },
}
</script>

<style>
ul {
  margin: 0;
  padding: 0;
}
li {
  list-style: none;
  margin: 0;
  padding: 0;
}
</style>
